In [27]:
import numpy as np

In [28]:
lenght = int(input("Enter the NxN Size  of the matrix: "))
matrix = np.zeros((lenght,lenght))

for i in range(0,lenght):
    for j in range(0,lenght):
        matrix[i][j] = int(input(f"Enter ({i},{j}) value :"))

value = np.zeros((lenght,1))
for i in range(0,lenght):
    value[i][0] = int(input(f"Enter {i} Vecor'svalue :"))

In [37]:
print(matrix,"\n\n",value)
b = np.array([[1],[2],[4]])

[[1. 1. 2.]
 [1. 2. 1.]
 [1. 1. 2.]] 

 [[1.]
 [2.]
 [3.]]


In [30]:
def is_Squared(x:np.array) -> bool:
    return np.shape(x) == (lenght,lenght)

def is_Transpose(x:np.array) -> bool:
    return x[0].shape == (1,)

def Gauss_Calculation(x:np.array) -> np.array:
    for i in range(0,lenght):
        pivot = x[i][i]
        for j in range(i+1,lenght):
                x[j] = x[j] - ((x[j][i])/pivot) *x[i]
        print("\n-----------------\n",x,"\n-----------------\n")

    return x
            
def Gauss_Eliminiration(x,y:np.array):
    if  is_Squared(x):
        if  is_Transpose(y):
            x = np.append(x,y,axis=1)
            print("Matrix is valid\n")
            return Gauss_Calculation(x)
            return x
        else:
            print("The Vector isn't Transposed\n")
    else:
        print("The Matrix isn't Squared\n")


In [43]:
print(Gauss_Eliminiration(matrix,value))

Matrix is valid


-----------------
 [[ 1.  1.  2.  1.]
 [ 0.  1. -1.  1.]
 [ 0.  0.  0.  3.]] 
-----------------


-----------------
 [[ 1.  1.  2.  1.]
 [ 0.  1. -1.  1.]
 [ 0.  0.  0.  3.]] 
-----------------


-----------------
 [[ 1.  1.  2.  1.]
 [ 0.  1. -1.  1.]
 [ 0.  0.  0.  3.]] 
-----------------

[[ 1.  1.  2.  1.]
 [ 0.  1. -1.  1.]
 [ 0.  0.  0.  3.]]
