In [7]:
import numpy as np

In [8]:
lenght = int(input("Enter the NxN Size  of the matrix: "))
matrix = np.zeros((lenght,lenght))

for i in range(0,lenght):
    for j in range(0,lenght):
        matrix[i][j] = int(input(f"Enter ({i},{j}) value :"))

value = np.zeros((lenght,1))
for i in range(0,lenght):
    value[i][0] = int(input(f"Enter {i} Vecor'svalue :"))

In [9]:
print(matrix,"\n\n",value)
b = np.array([[1],[2],[3]])

[[ 3.  2.  1.]
 [ 2. -1.  3.]
 [-1.  3.  2.]] 

 [[1.]
 [9.]
 [8.]]


In [ ]:
def is_Squared(x:np.array) -> bool:
    return np.shape(x) == (lenght,lenght)

def is_Transpose(x:np.array) -> bool:
    return x[0].shape == (1,)

def Gauss_Calculation(x:np.array) -> np.array:
    for i in range(0,lenght):
        pivot = x[i][i]
        x[i] *= 1/pivot
        for j in range(0,lenght):
            if j != i:
                x[j] = x[j] - ((x[j][i])) *x[i]
        print("\n-----------------\n",x,"\n-----------------\n")

    return x
            
def Gauss_Eliminiration(x,y:np.array):
    if  is_Squared(x):
        if  is_Transpose(y):
            x = np.append(x,y,axis=1)
            print("Matrix is valid\n")
            return Gauss_Calculation(x)
            return x
        else:
            print("The Vector isn't Transposed\n")
    else:
        print("The Matrix isn't Squared\n")
            

In [40]:
A = np.array([
    [3, 2, -1],
    [2, -1, 3],
    [-1, 3, 2]
], dtype=float)
B = np.array([
    [1],
    [9],
    [8]
], dtype=float)

In [ ]:
print(Gauss_Eliminiration(A,B))


Matrix is valid


-----------------
 [[ 1.          0.66666667 -0.33333333  0.33333333]
 [ 0.         -2.33333333  3.66666667  8.33333333]
 [ 0.          3.66666667  1.66666667  8.33333333]] 
-----------------


-----------------
 [[ 1.          0.          0.71428571  2.71428571]
 [-0.          1.         -1.57142857 -3.57142857]
 [ 0.          0.          7.42857143 21.42857143]] 
-----------------


-----------------
 [[1.         0.         0.         0.65384615]
 [0.         1.         0.         0.96153846]
 [0.         0.         1.         2.88461538]] 
-----------------

[[1.         0.         0.         0.65384615]
 [0.         1.         0.         0.96153846]
 [0.         0.         1.         2.88461538]]
